[package]
name = "postgres-update-table-check"
version = "0.1.0"
authors = ["gyomu_engineer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "4.0"
postgres = "0.15"